<template>
<div 
class="flex  flex-col justify-center relative  color-change-2x "
>
    <div class="flex self-center flex-col xl:flex-row justify-center max-w-[1440px] xl:px-36 px-4 gap-8 pb-[100px] xl:pb-[162px] pt-[100px] xl:pt-[200px] z-10 items-center w-full">
        <div class="rounded-3xl hover:scale-105 transition-all duration-300 shadow-2xl overflow-hidden h-[425px] w-full xl:w-2/5 bg-[url(/ctContacto.jpg)] bg-no-repeat bg-cover">        </div>

            <!-- <NuxtImg class="rounded-3xl !w-5/12" src="/ctContacto.png"></NuxtImg> -->
        <div class="bg-primary  hover:scale-105 transition-all duration-300 shadow-2xl  bg-[url(/ctContactoBg.svg)]  bg-no-repeat bg-right-bottom flex flex-col py-11 gap-4 text-white leading-tight xl:leading-[38px] items-start px-4 xl:px-0 xl:pl-[75px] w-full xl:w-2/3  rounded-[36px]  h-fit ">
            <p class="text-[30px] xl:text-[37px] font-medium">¡Trabajemos juntos!</p>
            <NuxtImg class="!h-auto !w-[54px]" src="/ctGuionC.svg"></NuxtImg>
            <p class="text-[24px] xl:text-[31px] font-medium">+54 9 11-21880434</p>
            <p class="text-[20px] xl:text-[31px] font-medium">carlos@carlosterzano.com</p>
        </div> 
    </div>  
    <!-- <div class="absolute flex h-full w-full "
    style="background: transparent linear-gradient(90deg, #4DE2BB 0%, #45CEB0 17%, #309D95 50%, #104D6A 97%, #0E4968 100%) 0% 0% no-repeat padding-box;
    mix-blend-mode: soft-light;
    opacity: 1;">
    </div>     -->
    <div class="w-full backgroundAnimado h-20"></div>
</div>
</template>
<script setup></script><style>
.backgroundAnimado{
  background: rgb(14,73,104);
  background: linear-gradient(0deg, rgba(14,73,104,1) 0%, rgba(14,73,104,0.8576680672268908) 39%, rgba(14,73,104,0.5775560224089635) 66%, rgba(255,255,255,0) 100%);
}
.color-change-2x {
	-webkit-animation: color-change-2x 3s linear infinite alternate both;
	        animation: color-change-2x 3s linear infinite alternate both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-8-19 12:21:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-2x
 * ----------------------------------------
 */
 @-webkit-keyframes color-change-2x {
  0% {
    background: #0E4968;
  }
  100% {
    background: #237094  ;
  }
}
@keyframes color-change-2x {
  0% {
    background: #104D6A ;
  }
  100% {
    background: #237094   ;
  }
}

</style>
